# Formulas and Functions

As said earlier, formulas are what makes spreadsheet a spreadsheet. You use formulas in your Excel worksheets to calculate results from the data stored in the worksheet. When data changes, the formulas calculate updated results with no extra effort on your part.

## Formula Basics

Formulas in Excel are expressions that perform calculations or operations on values in a worksheet. They can range from simple arithmetic calculations to sophisticated logical operations and statistical analyses. Excel formulas start with an equal sign (=) followed by any of these elements:

-   Mathematical operators such as + (for addition), \* (for multiplication)
-   Cell references (including named cells and ranges)
-   Values or text
-   Worksheet functions (such as `SUM` and `AVERAGE`)

After you enter the formula, excel displays the calculated result in the cell(s).

Few examples of formulas:

| Example                 | Formula                      |
|-------------------------|------------------------------|
| Simple Addition         | `=A1 + B1`                   |
| Multiplication          | `=A1 * B1`                   |
| SUM Function            | `=SUM(A1:A10)`               |
| AVERAGE Function        | `=AVERAGE(A1:A10)`           |
| IF Function             | `=IF(A1>10, "Pass", "Fail")` |
| Conditional Calculation | `=IF(A1>100, A1*10, A1*5)`   |

## Operators used in formulas

Operators are symbols that indicate what mathematical (or logical) operation you want the formula to perform.

| Operator | Name                                          |
|----------|-----------------------------------------------|
| \+       | Addition                                      |
| \-       | Subtraction                                   |
| \*       | Multiplication                                |
| /        | Division                                      |
| \^       | Exponentiation                                |
| &        | Concatenation                                 |
| =        | Logical comparison (equal to)                 |
| \>       | Logical comparison (greater than)             |
| \<       | Logical comparison (less than)                |
| \>=      | Logical comparison (greater than or equal to) |
| \<=      | Logical comparison (less than or equal to)    |
| \<\>     | Logical comparison (not equal to)             |

## Function Basics

A function is a predefined formula that performs calculations or task using specific values in a particular order. These functions are designed to simplify complex calculations and streamline repetitive tasks, saving you time and effort.

### Syntax

Every Excel function follows a standardized syntax, consisting of the function name, followed by parentheses enclosing one or more arguments. Arguments are the inputs provided to the function, which determine its behavior and output. Understanding the syntax of a function is crucial for using it correctly. Let's break it down:

``` default
=FUNCTION_NAME(argument1, argument2, ...)
```

-   **Function Name**: This is the name of the function that defines its purpose. Examples include SUM, AVERAGE, IF, VLOOKUP, etc.

-   **Arguments**: These are the values or cell references provided to the function to perform the desired calculation. The number and type of arguments vary depending on the function.

## Referencing Cells in Other Worksheets

To use a reference to a cell in another worksheet in the same workbook, use this format:

``` default
=SheetName!CellAddress
```

In other words, precede the cell address with the worksheet name followed by an exclamation point. Here's an example of a formula that uses a cell on the Sheet2 worksheet:

``` default
=A1*Sheet2!A1
```

This formula multiplies the value in cell A1 on the current worksheet by the value in cell A1 on Sheet2.

## Referencing Data in a Table

We have discussed about Excel Tables in @sec-tables.

Tables in Excel come with predefined headers for each column. These headers provide an intuitive way to reference data within the table. You can use these headers in formulas and functions to retrieve specific information.

For instance, you have a table named "PatientData" with columns: "Name", "Age", "Sex", "Days of Hospitalization". To find the average days of hospitalization, you can use the formula:

``` default
=AVERAGE(PatientData[Days of Hospitalization])
```

Here `PatientData[Days of Hospitalization]` refers to "Days of Hospitalization" column in the table "PatientData".

## Common Formula Errors

Sometimes when you enter a formula, Excel displays a value that begins with a hash mark (#). This is a signal that the formula is returning an error value. You have to correct the formula (or correct a cell that the formula references) to get rid of the error display.

| Error Value | Explanation                                                                                                                                                                                                                                                                                                                               |
|-----------------|-------------------------------------------------------|
| #DIV/0!     | The formula is trying to divide by zero. Because Excel applies a value of 0 to empty cells, this error also occurs when the formula attempts to divide by a cell that is blank or has a value of 0.                                                                                                                                       |
| #NAME?      | The formula uses a name that Excel doesn't recognize. This can happen if you delete a name that's used in the formula, if you misspell a name and then hit Enter, or if you have unmatched quotes when using text.                                                                                                                        |
| #N/A        | The formula is referring (directly or indirectly) to a cell that uses the NA function to signal that data is not available. For instance, the following formula returns an #N/A error if the A1 is empty: =IF(A1="", NA(), A1) Some lookup functions (for example, VLOOKUP and MATCH) can also return #N/A when they do not find a match. |
| #NULL!      | The formula uses an intersection of two ranges that don't intersect. (This concept is described later in the chapter.)                                                                                                                                                                                                                    |
| #NUM!       | A problem with a value exists; for example, you specified a negative number as an argument where a positive number is required.                                                                                                                                                                                                           |
| #REF!       | The formula refers to a cell that isn't valid. This can happen if the cell has been deleted from the worksheet.                                                                                                                                                                                                                           |
| #VALUE!     | The formula includes an argument or operand of the wrong type. (An operand is a value or cell reference that a formula uses to calculate a result.                                                                                                                                                                                        |

## Formula for Common Mathematical Operations

Like everyone who has to use Excel, public health students and professionals also will be asked to perform mathematical operations that provide insight into the data. We will see some examples of formulas that will help with this type of analyses.

## Calculating Percentages

Understanding the proportion of individual values in relation to the total is crucial for insightful analysis. Excel simplifies this task with the following formula:

``` default
= (Value / Total) * 100
```

Here, "Value" represents the specific data point you're interested in, and "Total" denotes the sum of all relevant values. By multiplying the quotient with 100, you obtain the percentage representation.

For example, suppose you have a dataset containing the number of cases of a disease for different states in a country and you want to calculate the percentage of the cases in each state out of the total cases in the country. You can use the formula `=(Cases in State / Total Cases in Country) * 100` to find the percentage for each region.

Dragging this formula across the dataset will swiftly compute the percentage of cases in each state. <br>

Analyzing variations between two data points is essential for detecting trends or anomalies. The formula for calculating percentage variance is:

``` default
= ((New Value - Old Value) / Old Value) * 100
```

In this formula, "New Value" signifies the updated or later data point, while "Old Value" represents the initial or previous data point. The difference between the new and old values, divided by the old value and multiplied by 100, yields the percentage variance.

Consider a scenario where you have data on the number of cases of a disease for two consecutive years. To calculate the percentage increase in cases from one year to the next, you can use the formula `=((Cases in Year 2 - Cases in Year 1) / Cases in Year 1) * 100`.

Executing this formula provides a clear percentage representation of the case variation, indicating whether cases have increased or decreased and by what percentage.

Exercise file is available [here](exercise/percentage.xlsx)

## Counting Values in a Range

Excel provides several functions to count the values in a range. They allow ypu to quickly tally up occurrences, quantify datasets, and derive valuable insights.

### COUNT() Function

The `COUNT()` function is a fundamental tool for counting numeric values within a dataset. It disregards empty cells and cells containing text or errors.

**Syntax:** `=COUNT(value1, [value2], ...)`

**Example:**

Consider a dataset containing the number of confirmed COVID-19 cases per day in a specific area:

| Day   | Confirmed Cases |
|-------|-----------------|
| Day 1 | 350             |
| Day 2 | 520             |
| Day 3 |                 |
| Day 4 | 430             |
| Day 5 | Error           |
| Day 6 | 650             |

To count the the total number of days with reported cases:

``` default
=COUNT(A2:A7)
```

This formula will return `4`, as there are four numeric values in the specified range.

### COUNTA() Function

While `COUNT()` tallies only numeric values, `COUNTA()` extends its capability to count all non-blank cells, including text and errors.

**Syntax:** `=COUNTA(value1, [value2], ...)`

**Example:**

Using the same dataset, let's count all non-blank cells:

``` default
=COUNTA(A2:A7)
```

This formula will return `5`, including both numeric values and the error.

### COUNTIF() Function

The `COUNTIF()` function is invaluable for counting cells that meet specific criteria within a dataset.

**Syntax:** `=COUNTIF(range, criteria)`

**Example:**

Suppose we want to count the number of days confirmed cases exceeding 400:

``` default
=COUNTIF(A2:A7, ">400")
```

This formula will return `3`, indicating there are three days in which number of daily confirmed cases were greater than 400.

### COUNTIFS() Function

Similar to `COUNTIF()`, `COUNTIFS()` extends its functionality to count cells based on multiple criteria.

**Syntax:** `=COUNTIFS(criteria_range1, criteria1, [criteria_range2, criteria2], ...)`

**Example:**

Consider a scenario where we want to count the days with more than 100 cases in a specific region. We can use COUNTIFS() to achieve this by specifying both the region and the case count threshold.

``` default
=COUNTIFS(A2:A7, ">400", B2:B7, "Region A")
```





> Excel enables you to enter flexible formulas that use the values (or even text) in cells to calculate a result. When you enter a formula into a cell, the formula's result appears in the cell. If you change any of the cells used by a formula, the formula recalculates and shows the new result.[@allen2017]

> abs
round
count
sum
sumif
vlookup
xlookup
index match
if
ifs
textjoin
concatenate
sentence case
trim
left
right
mid
len
today
now
="Today is "&TEXT(TODAY(),"mmmm d, yyyy")
datedif
extract year monmth day
