project:
  type: book

book:
  title: "Excel for Public Health Students"
  author: "Razi N"
  page-footer:
    left:  |
      Excel for Public Health Students
    right: |
      This book was written using <a href="https://quarto.org/">Quarto</a>.
  chapters:
    - index.qmd
    - intro.qmd
    - formula.qmd
    - visualizations.qmd
    - analysis.qmd
    - power_query.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

